//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xave.com.generator.cus.StructureSetModel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Containers", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class Containers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.BodyStructure[] BodyStructureTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.Document[] DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.HeaderMap[] HeaderMapTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.HeaderPart[] HeaderPartTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.HeaderStructure[] HeaderStructureTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.SectionMap[] SectionMapTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.SectionPart[] SectionPartTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.Section[] SectionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.BodyStructure[] BodyStructureType {
            get {
                return this.BodyStructureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyStructureTypeField, value) != true)) {
                    this.BodyStructureTypeField = value;
                    this.RaisePropertyChanged("BodyStructureType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.Document[] DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.HeaderMap[] HeaderMapType {
            get {
                return this.HeaderMapTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderMapTypeField, value) != true)) {
                    this.HeaderMapTypeField = value;
                    this.RaisePropertyChanged("HeaderMapType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.HeaderPart[] HeaderPartType {
            get {
                return this.HeaderPartTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderPartTypeField, value) != true)) {
                    this.HeaderPartTypeField = value;
                    this.RaisePropertyChanged("HeaderPartType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.HeaderStructure[] HeaderStructureType {
            get {
                return this.HeaderStructureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderStructureTypeField, value) != true)) {
                    this.HeaderStructureTypeField = value;
                    this.RaisePropertyChanged("HeaderStructureType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.SectionMap[] SectionMapType {
            get {
                return this.SectionMapTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionMapTypeField, value) != true)) {
                    this.SectionMapTypeField = value;
                    this.RaisePropertyChanged("SectionMapType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.SectionPart[] SectionPartType {
            get {
                return this.SectionPartTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionPartTypeField, value) != true)) {
                    this.SectionPartTypeField = value;
                    this.RaisePropertyChanged("SectionPartType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.Section[] SectionType {
            get {
                return this.SectionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionTypeField, value) != true)) {
                    this.SectionTypeField = value;
                    this.RaisePropertyChanged("SectionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BodyStructure", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class BodyStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PathSplitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionPartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BindType {
            get {
                return this.BindTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BindTypeField, value) != true)) {
                    this.BindTypeField = value;
                    this.RaisePropertyChanged("BindType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Group {
            get {
                return this.GroupField;
            }
            set {
                if ((this.GroupField.Equals(value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((this.ParentField.Equals(value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PathSplited {
            get {
                return this.PathSplitedField;
            }
            set {
                if ((object.ReferenceEquals(this.PathSplitedField, value) != true)) {
                    this.PathSplitedField = value;
                    this.RaisePropertyChanged("PathSplited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property {
            get {
                return this.PropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyField, value) != true)) {
                    this.PropertyField = value;
                    this.RaisePropertyChanged("Property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionPartId {
            get {
                return this.SectionPartIdField;
            }
            set {
                if ((this.SectionPartIdField.Equals(value) != true)) {
                    this.SectionPartIdField = value;
                    this.RaisePropertyChanged("SectionPartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueType {
            get {
                return this.ValueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueTypeField, value) != true)) {
                    this.ValueTypeField = value;
                    this.RaisePropertyChanged("ValueType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSystemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.HeaderPart[] HeaderPartListTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealmCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.Section[] SectionListTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSystem {
            get {
                return this.CodeSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSystemField, value) != true)) {
                    this.CodeSystemField = value;
                    this.RaisePropertyChanged("CodeSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSystemName {
            get {
                return this.CodeSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSystemNameField, value) != true)) {
                    this.CodeSystemNameField = value;
                    this.RaisePropertyChanged("CodeSystemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocType {
            get {
                return this.DocTypeField;
            }
            set {
                if ((this.DocTypeField.Equals(value) != true)) {
                    this.DocTypeField = value;
                    this.RaisePropertyChanged("DocType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTypeCode {
            get {
                return this.DocTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocTypeCodeField, value) != true)) {
                    this.DocTypeCodeField = value;
                    this.RaisePropertyChanged("DocTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTypeName {
            get {
                return this.DocTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocTypeNameField, value) != true)) {
                    this.DocTypeNameField = value;
                    this.RaisePropertyChanged("DocTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.HeaderPart[] HeaderPartListType {
            get {
                return this.HeaderPartListTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderPartListTypeField, value) != true)) {
                    this.HeaderPartListTypeField = value;
                    this.RaisePropertyChanged("HeaderPartListType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealmCode {
            get {
                return this.RealmCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RealmCodeField, value) != true)) {
                    this.RealmCodeField = value;
                    this.RaisePropertyChanged("RealmCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.Section[] SectionListType {
            get {
                return this.SectionListTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionListTypeField, value) != true)) {
                    this.SectionListTypeField = value;
                    this.RaisePropertyChanged("SectionListType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateIdField, value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderMap", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class HeaderMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeaderPartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((this.DocumentIdField.Equals(value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeaderPartId {
            get {
                return this.HeaderPartIdField;
            }
            set {
                if ((this.HeaderPartIdField.Equals(value) != true)) {
                    this.HeaderPartIdField = value;
                    this.RaisePropertyChanged("HeaderPartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderPart", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class HeaderPart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.HeaderStructure[] StructureSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.HeaderStructure[] StructureSet {
            get {
                return this.StructureSetField;
            }
            set {
                if ((object.ReferenceEquals(this.StructureSetField, value) != true)) {
                    this.StructureSetField = value;
                    this.RaisePropertyChanged("StructureSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderStructure", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class HeaderStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeaderPartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PathSplitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeaderPartId {
            get {
                return this.HeaderPartIdField;
            }
            set {
                if ((this.HeaderPartIdField.Equals(value) != true)) {
                    this.HeaderPartIdField = value;
                    this.RaisePropertyChanged("HeaderPartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((this.ParentField.Equals(value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PathSplited {
            get {
                return this.PathSplitedField;
            }
            set {
                if ((object.ReferenceEquals(this.PathSplitedField, value) != true)) {
                    this.PathSplitedField = value;
                    this.RaisePropertyChanged("PathSplited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueType {
            get {
                return this.ValueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueTypeField, value) != true)) {
                    this.ValueTypeField = value;
                    this.RaisePropertyChanged("ValueType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SectionMap", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class SectionMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((this.DocumentIdField.Equals(value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId {
            get {
                return this.SectionIdField;
            }
            set {
                if ((this.SectionIdField.Equals(value) != true)) {
                    this.SectionIdField = value;
                    this.RaisePropertyChanged("SectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SectionPart", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class SectionPart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.BodyStructure[] BodyStructureListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.SectionPart[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSystemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateIdExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateIdRootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BindType {
            get {
                return this.BindTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BindTypeField, value) != true)) {
                    this.BindTypeField = value;
                    this.RaisePropertyChanged("BindType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.BodyStructure[] BodyStructureList {
            get {
                return this.BodyStructureListField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyStructureListField, value) != true)) {
                    this.BodyStructureListField = value;
                    this.RaisePropertyChanged("BodyStructureList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.SectionPart[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSystem {
            get {
                return this.CodeSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSystemField, value) != true)) {
                    this.CodeSystemField = value;
                    this.RaisePropertyChanged("CodeSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSystemName {
            get {
                return this.CodeSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSystemNameField, value) != true)) {
                    this.CodeSystemNameField = value;
                    this.RaisePropertyChanged("CodeSystemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeType {
            get {
                return this.CodeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeTypeField, value) != true)) {
                    this.CodeTypeField = value;
                    this.RaisePropertyChanged("CodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((this.ParentField.Equals(value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId {
            get {
                return this.SectionIdField;
            }
            set {
                if ((this.SectionIdField.Equals(value) != true)) {
                    this.SectionIdField = value;
                    this.RaisePropertyChanged("SectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionType {
            get {
                return this.SectionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionTypeField, value) != true)) {
                    this.SectionTypeField = value;
                    this.RaisePropertyChanged("SectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateIdExtension {
            get {
                return this.TemplateIdExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateIdExtensionField, value) != true)) {
                    this.TemplateIdExtensionField = value;
                    this.RaisePropertyChanged("TemplateIdExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateIdRoot {
            get {
                return this.TemplateIdRootField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateIdRootField, value) != true)) {
                    this.TemplateIdRootField = value;
                    this.RaisePropertyChanged("TemplateIdRoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueType {
            get {
                return this.ValueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueTypeField, value) != true)) {
                    this.ValueTypeField = value;
                    this.RaisePropertyChanged("ValueType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Section", Namespace="http://schemas.datacontract.org/2004/07/xave.web.structureset.dto")]
    [System.SerializableAttribute()]
    public partial class Section : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindableVariableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSystemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.SectionPart[] EntryListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private xave.com.generator.cus.StructureSetModel.SectionPart[] NarrativeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateIdExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateIdRootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseYNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BindableVariable {
            get {
                return this.BindableVariableField;
            }
            set {
                if ((object.ReferenceEquals(this.BindableVariableField, value) != true)) {
                    this.BindableVariableField = value;
                    this.RaisePropertyChanged("BindableVariable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSystem {
            get {
                return this.CodeSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSystemField, value) != true)) {
                    this.CodeSystemField = value;
                    this.RaisePropertyChanged("CodeSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSystemName {
            get {
                return this.CodeSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSystemNameField, value) != true)) {
                    this.CodeSystemNameField = value;
                    this.RaisePropertyChanged("CodeSystemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.SectionPart[] EntryList {
            get {
                return this.EntryListField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryListField, value) != true)) {
                    this.EntryListField = value;
                    this.RaisePropertyChanged("EntryList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public xave.com.generator.cus.StructureSetModel.SectionPart[] NarrativeList {
            get {
                return this.NarrativeListField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrativeListField, value) != true)) {
                    this.NarrativeListField = value;
                    this.RaisePropertyChanged("NarrativeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateIdExtension {
            get {
                return this.TemplateIdExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateIdExtensionField, value) != true)) {
                    this.TemplateIdExtensionField = value;
                    this.RaisePropertyChanged("TemplateIdExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateIdRoot {
            get {
                return this.TemplateIdRootField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateIdRootField, value) != true)) {
                    this.TemplateIdRootField = value;
                    this.RaisePropertyChanged("TemplateIdRoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseYN {
            get {
                return this.UseYNField;
            }
            set {
                if ((object.ReferenceEquals(this.UseYNField, value) != true)) {
                    this.UseYNField = value;
                    this.RaisePropertyChanged("UseYN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StructureSetModel.IStructureSetModel")]
    public interface IStructureSetModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStructureSetModel/GetModel", ReplyAction="http://tempuri.org/IStructureSetModel/GetModelResponse")]
        void GetModel(xave.com.generator.cus.StructureSetModel.Containers containers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStructureSetModel/GetModel", ReplyAction="http://tempuri.org/IStructureSetModel/GetModelResponse")]
        System.Threading.Tasks.Task GetModelAsync(xave.com.generator.cus.StructureSetModel.Containers containers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStructureSetModelChannel : xave.com.generator.cus.StructureSetModel.IStructureSetModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StructureSetModelClient : System.ServiceModel.ClientBase<xave.com.generator.cus.StructureSetModel.IStructureSetModel>, xave.com.generator.cus.StructureSetModel.IStructureSetModel {
        
        public StructureSetModelClient() {
        }
        
        public StructureSetModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StructureSetModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StructureSetModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StructureSetModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetModel(xave.com.generator.cus.StructureSetModel.Containers containers) {
            base.Channel.GetModel(containers);
        }
        
        public System.Threading.Tasks.Task GetModelAsync(xave.com.generator.cus.StructureSetModel.Containers containers) {
            return base.Channel.GetModelAsync(containers);
        }
    }
}
